In [3]:
import pandas as pd
import time
import re

In [4]:
# Seasons to scrape
seasons = list(range(2010, 2025))  # 2010 through 2024

# Base URL pattern
base_url = "https://www.pro-football-reference.com/years/{}/fantasy.htm"

# List to hold all DataFrames
fantasy_data = []

for season in seasons:
    print(f"Scraping {season} data...")
    url = base_url.format(season)
    try:
        tables = pd.read_html(url)
        df = tables[0]
        df['Season'] = season  # Add season info
        fantasy_data.append(df)
        time.sleep(2)  # Be polite to the server
    except Exception as e:
        print(f"Failed to retrieve data for {season}: {e}")

# Combine all data
all_fantasy_df = pd.concat(fantasy_data, ignore_index=True)

# Preview
print(all_fantasy_df.head())
print(f"\nData collected for {len(seasons)} seasons with {len(all_fantasy_df)} total rows.")

Scraping 2010 data...
Scraping 2011 data...
Scraping 2012 data...
Scraping 2013 data...
Scraping 2014 data...
Scraping 2015 data...
Scraping 2016 data...
Scraping 2017 data...
Scraping 2018 data...
Scraping 2019 data...
Scraping 2020 data...
Scraping 2021 data...
Scraping 2022 data...
Scraping 2023 data...
Scraping 2024 data...
  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player                 Tm            FantPos
0                  1     Arian Foster*+                HOU                 RB
1                  2   Adrian Peterson*                MIN                 RB
2                  3   Jamaal Charles*+                KAN                 RB
3                  4      Peyton Hillis                CLE                 RB
4                  5     Chris Johnson*                TEN                 RB

  Unnamed: 4_level_0 Games     Passing          ... Scoring      Fantasy  \
                 Age     G  GS     Cmp Att Yds  ...     2PM  2PP  FantPt
0                 24    16  13       0   0   0  ...     NaN  NaN     326
1                 25    15  15       0   0   0  ...     NaN  NaN     240
2                 24    16   6       0   0   0  ...     NaN  NaN     238
3                 24    16  14       1   2  13  ...     NaN  NaN     234
4                 25    16  16       0   0   0  ...     NaN  NaN     229

                                           Season
     PPR   DKPt   FDPt  VBD PosRank OvRank
0  392.0  400.0  359.0  190       1      1   2010
1  275.9  282.9  257.9  104       2      2   2010
2  282.5  290.5  260.0  102       3      3   2010
3  294.9  305.9  264.4   98       4      4   2010
4  272.9  280.9  250.9   93       5      5   2010

[5 rows x 34 columns]

Data collected for 15 seasons with 9527 total rows.

In [5]:
all_fantasy_df.to_pickle('all_fantasy_df.pkl')

In [6]:
df = pd.read_pickle('all_fantasy_df.pkl')

In [7]:
df

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player                 Tm
0                     1     Arian Foster*+                HOU
1                     2   Adrian Peterson*                MIN
2                     3   Jamaal Charles*+                KAN
3                     4      Peyton Hillis                CLE
4                     5     Chris Johnson*                TEN
...                 ...                ...                ...
9522                627        Steven Sims                2TM
9523                628     Kadarius Toney                CLE
9524                629       Clayton Tune                ARI
9525                 Rk             Player                 Tm
9526                630   Jha'Quan Jackson                TEN

     Unnamed: 3_level_0 Unnamed: 4_level_0 Games     Passing            ...  \
                FantPos                Age     G  GS     Cmp  Att  Yds  ...
0                    RB                 24    16  13       0    0    0  ...
1                    RB                 25    15  15       0    0    0  ...
2                    RB                 24    16   6       0    0    0  ...
3                    RB                 24    16  14       1    2   13  ...
4                    RB                 25    16  16       0    0    0  ...
...                 ...                ...   ...  ..     ...  ...  ...  ...
9522                 WR                 27     9   0       0    0    0  ...
9523                 WR                 25     3   0       0    0    0  ...
9524                 QB                 25     6   0       2    2    8  ...
9525            FantPos                Age     G  GS     Cmp  Att  Yds  ...
9526                 WR                 24    12   0       0    0    0  ...

     Scoring      Fantasy                                            Season
         2PM  2PP  FantPt    PPR   DKPt   FDPt  VBD  PosRank  OvRank
0        NaN  NaN     326  392.0  400.0  359.0  190        1       1   2010
1        NaN  NaN     240  275.9  282.9  257.9  104        2       2   2010
2        NaN  NaN     238  282.5  290.5  260.0  102        3       3   2010
3        NaN  NaN     234  294.9  305.9  264.4   98        4       4   2010
4        NaN  NaN     229  272.9  280.9  250.9   93        5       5   2010
...      ...  ...     ...    ...    ...    ...  ...      ...     ...    ...
9522     NaN  NaN      -2   -2.0   -1.0   -2.0  NaN      248     NaN   2024
9523     NaN  NaN      -2   -2.4   -1.4   -2.4  NaN      249     NaN   2024
9524     NaN  NaN      -2   -2.1   -1.1   -2.1  NaN       79     NaN   2024
9525     2PM  2PP  FantPt    PPR   DKPt   FDPt  VBD  PosRank  OvRank   2024
9526     NaN  NaN      -4   -2.7   -0.7   -3.2  NaN      250     NaN   2024

[9527 rows x 34 columns]

In [8]:
df.columns.tolist()

[('Unnamed: 0_level_0', 'Rk'),
 ('Unnamed: 1_level_0', 'Player'),
 ('Unnamed: 2_level_0', 'Tm'),
 ('Unnamed: 3_level_0', 'FantPos'),
 ('Unnamed: 4_level_0', 'Age'),
 ('Games', 'G'),
 ('Games', 'GS'),
 ('Passing', 'Cmp'),
 ('Passing', 'Att'),
 ('Passing', 'Yds'),
 ('Passing', 'TD'),
 ('Passing', 'Int'),
 ('Rushing', 'Att'),
 ('Rushing', 'Yds'),
 ('Rushing', 'Y/A'),
 ('Rushing', 'TD'),
 ('Receiving', 'Tgt'),
 ('Receiving', 'Rec'),
 ('Receiving', 'Yds'),
 ('Receiving', 'Y/R'),
 ('Receiving', 'TD'),
 ('Fumbles', 'Fmb'),
 ('Fumbles', 'FL'),
 ('Scoring', 'TD'),
 ('Scoring', '2PM'),
 ('Scoring', '2PP'),
 ('Fantasy', 'FantPt'),
 ('Fantasy', 'PPR'),
 ('Fantasy', 'DKPt'),
 ('Fantasy', 'FDPt'),
 ('Fantasy', 'VBD'),
 ('Fantasy', 'PosRank'),
 ('Fantasy', 'OvRank'),
 ('Season', '')]

In [9]:
def flatten_col(col_tuple):
    return '_'.join([str(c) for c in col_tuple if c]).strip('_')

In [10]:
df.columns = [flatten_col(col) for col in df.columns]

In [11]:
rename_dict = {
    'Unnamed: 0_level_0_Rk': 'Rk',
    'Unnamed: 1_level_0_Player': 'Player',
    'Unnamed: 2_level_0_Tm': 'Tm',
    'Unnamed: 3_level_0_FantPos': 'FantPos',
    'Unnamed: 4_level_0_Age': 'Age',
}

In [12]:
df.rename(columns=rename_dict, inplace=True)

In [13]:
clean_df = df[df['Player'] != 'Player'].copy()

In [14]:
clean_df

,Rk,Player,Tm,FantPos,Age,Games_G,Games_GS,Passing_Cmp,Passing_Att,Passing_Yds,...,Scoring_2PM,Scoring_2PP,Fantasy_FantPt,Fantasy_PPR,Fantasy_DKPt,Fantasy_FDPt,Fantasy_VBD,Fantasy_PosRank,Fantasy_OvRank,Season
0,1,Arian Foster*+,HOU,RB,24,16,13,0,0,0,...,NaN,NaN,326,392.0,400.0,359.0,190,1,1,2010
1,2,Adrian Peterson*,MIN,RB,25,15,15,0,0,0,...,NaN,NaN,240,275.9,282.9,257.9,104,2,2,2010
2,3,Jamaal Charles*+,KAN,RB,24,16,6,0,0,0,...,NaN,NaN,238,282.5,290.5,260.0,102,3,3,2010
3,4,Peyton Hillis,CLE,RB,24,16,14,1,2,13,...,NaN,NaN,234,294.9,305.9,264.4,98,4,4,2010
4,5,Chris Johnson*,TEN,RB,25,16,16,0,0,0,...,NaN,NaN,229,272.9,280.9,250.9,93,5,5,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9521,626,Dylan Laube,LVR,RB,25,10,0,0,0,0,...,NaN,NaN,-2,-2.0,-1.0,-2.0,NaN,156,NaN,2024
9522,627,Steven Sims,2TM,WR,27,9,0,0,0,0,...,NaN,NaN,-2,-2.0,-1.0,-2.0,NaN,248,NaN,2024
9523,628,Kadarius Toney,CLE,WR,25,3,0,0,0,0,...,NaN,NaN,-2,-2.4,-1.4,-2.4,NaN,249,NaN,2024
9524,629,Clayton Tune,ARI,QB,25,6,0,2,2,8,...,NaN,NaN,-2,-2.1,-1.1,-2.1,NaN,79,NaN,2024
9526,630,Jha'Quan Jackson,TEN,WR,24,12,0,0,0,0,...,NaN,NaN,-4,-2.7,-0.7,-3.2,NaN,250,NaN,2024

In [15]:
clean_df.reset_index(drop=True, inplace=True)

In [16]:
clean_df.to_csv('clean_fantasy_data.csv', index=False)

In [17]:
clean_df = pd.read_csv('clean_fantasy_data.csv')

In [18]:
def clean_player_name(name):
    # Remove trailing non-letter characters (like *, +, etc.) from the end of the string
    return re.sub(r'[\W_]+$', '', name)

In [19]:
clean_df['Player'] = clean_df['Player'].astype(str).apply(clean_player_name)

In [20]:
clean_df

,Rk,Player,Tm,FantPos,Age,Games_G,Games_GS,Passing_Cmp,Passing_Att,Passing_Yds,...,Scoring_2PM,Scoring_2PP,Fantasy_FantPt,Fantasy_PPR,Fantasy_DKPt,Fantasy_FDPt,Fantasy_VBD,Fantasy_PosRank,Fantasy_OvRank,Season
0,1,Arian Foster,HOU,RB,24,16,13.0,0.0,0.0,0.0,...,NaN,NaN,326.0,392.0,400.0,359.0,190.0,1,1.0,2010
1,2,Adrian Peterson,MIN,RB,25,15,15.0,0.0,0.0,0.0,...,NaN,NaN,240.0,275.9,282.9,257.9,104.0,2,2.0,2010
2,3,Jamaal Charles,KAN,RB,24,16,6.0,0.0,0.0,0.0,...,NaN,NaN,238.0,282.5,290.5,260.0,102.0,3,3.0,2010
3,4,Peyton Hillis,CLE,RB,24,16,14.0,1.0,2.0,13.0,...,NaN,NaN,234.0,294.9,305.9,264.4,98.0,4,4.0,2010
4,5,Chris Johnson,TEN,RB,25,16,16.0,0.0,0.0,0.0,...,NaN,NaN,229.0,272.9,280.9,250.9,93.0,5,5.0,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9222,626,Dylan Laube,LVR,RB,25,10,0.0,0.0,0.0,0.0,...,NaN,NaN,-2.0,-2.0,-1.0,-2.0,NaN,156,NaN,2024
9223,627,Steven Sims,2TM,WR,27,9,0.0,0.0,0.0,0.0,...,NaN,NaN,-2.0,-2.0,-1.0,-2.0,NaN,248,NaN,2024
9224,628,Kadarius Toney,CLE,WR,25,3,0.0,0.0,0.0,0.0,...,NaN,NaN,-2.0,-2.4,-1.4,-2.4,NaN,249,NaN,2024
9225,629,Clayton Tune,ARI,QB,25,6,0.0,2.0,2.0,8.0,...,NaN,NaN,-2.0,-2.1,-1.1,-2.1,NaN,79,NaN,2024
9226,630,Jha'Quan Jackson,TEN,WR,24,12,0.0,0.0,0.0,0.0,...,NaN,NaN,-4.0,-2.7,-0.7,-3.2,NaN,250,NaN,2024

In [21]:
clean_df['Season'] = clean_df['Season'].astype(int)

In [22]:
clean_df = clean_df.sort_values(['Player', 'Season'])

In [23]:
clean_df

,Rk,Player,Tm,FantPos,Age,Games_G,Games_GS,Passing_Cmp,Passing_Att,Passing_Yds,...,Scoring_2PM,Scoring_2PP,Fantasy_FantPt,Fantasy_PPR,Fantasy_DKPt,Fantasy_FDPt,Fantasy_VBD,Fantasy_PosRank,Fantasy_OvRank,Season
5383,34,A.J. Brown,TEN,WR,22,16,11.0,0.0,0.0,0.0,...,NaN,NaN,165.0,217.1,220.1,191.1,36.0,9,34.0,2019
5993,29,A.J. Brown,TEN,WR,23,14,12.0,0.0,0.0,0.0,...,NaN,NaN,178.0,247.5,251.5,212.5,51.0,9,29.0,2020
6723,102,A.J. Brown,TEN,WR,24,13,13.0,0.0,2.0,0.0,...,NaN,NaN,118.0,180.9,183.9,149.4,NaN,32,NaN,2021
7328,13,A.J. Brown,PHI,WR,25,17,16.0,0.0,0.0,0.0,...,NaN,NaN,212.0,299.6,304.6,255.6,91.0,4,13.0,2022
7984,20,A.J. Brown,PHI,WR,26,17,17.0,0.0,0.0,0.0,...,NaN,NaN,184.0,289.6,294.6,236.6,51.0,8,20.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9001,405,Zay Jones,ARI,WR,29,11,2.0,0.0,0.0,0.0,...,NaN,NaN,8.0,16.4,16.4,12.4,NaN,155,NaN,2024
7549,234,Zonovan Knight,NYJ,RB,21,7,4.0,0.0,0.0,0.0,...,NaN,NaN,46.0,59.0,65.0,52.5,NaN,66,NaN,2022
8455,491,Zonovan Knight,DET,RB,22,2,0.0,0.0,0.0,0.0,...,NaN,NaN,2.0,3.1,3.1,2.6,NaN,127,NaN,2023
2699,354,Zurlon Tipton,IND,RB,24,6,0.0,0.0,0.0,0.0,...,NaN,NaN,15.0,20.6,20.6,17.6,NaN,110,NaN,2014
3377,436,Zurlon Tipton,IND,RB,25,10,0.0,0.0,0.0,0.0,...,NaN,NaN,8.0,12.7,12.7,10.2,NaN,127,NaN,2015

In [24]:
clean_df.columns.to_list()

['Rk',
 'Player',
 'Tm',
 'FantPos',
 'Age',
 'Games_G',
 'Games_GS',
 'Passing_Cmp',
 'Passing_Att',
 'Passing_Yds',
 'Passing_TD',
 'Passing_Int',
 'Rushing_Att',
 'Rushing_Yds',
 'Rushing_Y/A',
 'Rushing_TD',
 'Receiving_Tgt',
 'Receiving_Rec',
 'Receiving_Yds',
 'Receiving_Y/R',
 'Receiving_TD',
 'Fumbles_Fmb',
 'Fumbles_FL',
 'Scoring_TD',
 'Scoring_2PM',
 'Scoring_2PP',
 'Fantasy_FantPt',
 'Fantasy_PPR',
 'Fantasy_DKPt',
 'Fantasy_FDPt',
 'Fantasy_VBD',
 'Fantasy_PosRank',
 'Fantasy_OvRank',
 'Season']

In [25]:
features_to_lag = [
    'Age', 
    'Games_G', 
    'Games_GS',
    'Passing_Cmp', 
    'Passing_Att', 
    'Passing_Yds', 
    'Passing_TD', 
    'Passing_Int',
    'Rushing_Att', 
    'Rushing_Yds', 
    'Rushing_TD', 
    'Rushing_Y/A',
    'Receiving_Tgt', 
    'Receiving_Rec', 
    'Receiving_Yds', 
    'Receiving_TD', 
    'Receiving_Y/R',
    'Fumbles_Fmb', 
    'Fumbles_FL',
    'Scoring_TD', 
    'Scoring_2PM', 
    'Scoring_2PP',
    'Tm', 
    'FantPos',  # these will be encoded later
    'Fantasy_FantPt'
]

In [26]:
# Shift each feature by 1 season per player
for feature in features_to_lag:
    clean_df[f'{feature}_prev1'] = clean_df.groupby('Player')[feature].shift(1)

In [27]:
clean_df

,Rk,Player,Tm,FantPos,Age,Games_G,Games_GS,Passing_Cmp,Passing_Att,Passing_Yds,...,Receiving_TD_prev1,Receiving_Y/R_prev1,Fumbles_Fmb_prev1,Fumbles_FL_prev1,Scoring_TD_prev1,Scoring_2PM_prev1,Scoring_2PP_prev1,Tm_prev1,FantPos_prev1,Fantasy_FantPt_prev1
5383,34,A.J. Brown,TEN,WR,22,16,11.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5993,29,A.J. Brown,TEN,WR,23,14,12.0,0.0,0.0,0.0,...,8.0,20.21,1.0,0.0,9.0,NaN,NaN,TEN,WR,165.0
6723,102,A.J. Brown,TEN,WR,24,13,13.0,0.0,2.0,0.0,...,11.0,15.36,2.0,1.0,12.0,NaN,NaN,TEN,WR,178.0
7328,13,A.J. Brown,PHI,WR,25,17,16.0,0.0,0.0,0.0,...,5.0,13.79,0.0,0.0,5.0,NaN,NaN,TEN,WR,118.0
7984,20,A.J. Brown,PHI,WR,26,17,17.0,0.0,0.0,0.0,...,11.0,17.00,2.0,2.0,11.0,NaN,NaN,PHI,WR,212.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9001,405,Zay Jones,ARI,WR,29,11,2.0,0.0,0.0,0.0,...,2.0,9.44,0.0,0.0,2.0,NaN,NaN,JAX,WR,44.0
7549,234,Zonovan Knight,NYJ,RB,21,7,4.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8455,491,Zonovan Knight,DET,RB,22,2,0.0,0.0,0.0,0.0,...,0.0,7.69,2.0,0.0,1.0,NaN,NaN,NYJ,RB,46.0
2699,354,Zurlon Tipton,IND,RB,24,6,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3377,436,Zurlon Tipton,IND,RB,25,10,0.0,0.0,0.0,0.0,...,1.0,11.33,0.0,0.0,1.0,NaN,NaN,IND,RB,15.0

In [28]:
# Only use rows where the next season's fantasy points are known
model_df = clean_df.dropna(subset=['Fantasy_FantPt_prev1'])

In [29]:
model_df

,Rk,Player,Tm,FantPos,Age,Games_G,Games_GS,Passing_Cmp,Passing_Att,Passing_Yds,...,Receiving_TD_prev1,Receiving_Y/R_prev1,Fumbles_Fmb_prev1,Fumbles_FL_prev1,Scoring_TD_prev1,Scoring_2PM_prev1,Scoring_2PP_prev1,Tm_prev1,FantPos_prev1,Fantasy_FantPt_prev1
5993,29,A.J. Brown,TEN,WR,23,14,12.0,0.0,0.0,0.0,...,8.0,20.21,1.0,0.0,9.0,NaN,NaN,TEN,WR,165.0
6723,102,A.J. Brown,TEN,WR,24,13,13.0,0.0,2.0,0.0,...,11.0,15.36,2.0,1.0,12.0,NaN,NaN,TEN,WR,178.0
7328,13,A.J. Brown,PHI,WR,25,17,16.0,0.0,0.0,0.0,...,5.0,13.79,0.0,0.0,5.0,NaN,NaN,TEN,WR,118.0
7984,20,A.J. Brown,PHI,WR,26,17,17.0,0.0,0.0,0.0,...,11.0,17.00,2.0,2.0,11.0,NaN,NaN,PHI,WR,212.0
8651,55,A.J. Brown,PHI,WR,27,13,13.0,0.0,0.0,0.0,...,7.0,13.74,2.0,2.0,7.0,NaN,NaN,PHI,WR,184.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7385,70,Zay Jones,JAX,WR,27,16,15.0,0.0,0.0,0.0,...,1.0,11.62,1.0,1.0,1.0,NaN,NaN,LVR,WR,59.0
8191,227,Zay Jones,JAX,WR,28,9,7.0,0.0,0.0,0.0,...,5.0,10.04,0.0,0.0,5.0,1.0,NaN,JAX,WR,116.0
9001,405,Zay Jones,ARI,WR,29,11,2.0,0.0,0.0,0.0,...,2.0,9.44,0.0,0.0,2.0,NaN,NaN,JAX,WR,44.0
8455,491,Zonovan Knight,DET,RB,22,2,0.0,0.0,0.0,0.0,...,0.0,7.69,2.0,0.0,1.0,NaN,NaN,NYJ,RB,46.0
3377,436,Zurlon Tipton,IND,RB,25,10,0.0,0.0,0.0,0.0,...,1.0,11.33,0.0,0.0,1.0,NaN,NaN,IND,RB,15.0

In [30]:
model_df.to_csv('model_df.csv', index=False)